In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.linear_model import ElasticNet
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor as KNN
from xgboost import XGBRegressor
from sklearn.metrics import r2_score

from sklearn.model_selection import cross_val_score
import optuna as opt

c:\Users\ACER\miniconda3\envs\agentic\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [4]:
dataset=pd.read_csv(r"D:\Downloads\agentic_reality.csv")
dataset.head(n=10)

,Project_ID,Industry,Agent_Type,Primary_Tool,Status,Failure_Reason,Human_in_the_Loop_Ratio,Tokens_per_Task,ROI_Score
0,AGP-0001,Insurance,Autonomous,LangGraph,Production,NaN,0.389,2094,2.51
1,AGP-0002,Retail,Assistant,CrewAI,Production,NaN,0.990,5993,3.78
2,AGP-0003,Energy,Multi-agent Swarm,AutoGPT 3.0,Pilot,Loop Error,0.475,9032,0.91
3,AGP-0004,Technology,Multi-agent Swarm,LangGraph,Pilot,Loop Error,0.372,8735,0.75
4,AGP-0005,Finance,Autonomous,LangGraph,Production,NaN,0.613,1645,2.58
5,AGP-0006,Telecom,Autonomous,CrewAI,Abandoned,Schema Drift,0.168,3713,-0.38
6,AGP-0007,Insurance,Multi-agent Swarm,AutoGPT 3.0,Abandoned,Schema Drift,0.478,10530,-1.51
7,AGP-0008,Insurance,Multi-agent Swarm,CrewAI,Abandoned,Cost Overrun,0.224,6478,-0.71
8,AGP-0009,Finance,Assistant,CrewAI,Production,NaN,0.795,2821,1.22
9,AGP-0010,Retail,Assistant,LangGraph,Production,NaN,0.724,4428,4.49

In [5]:
dataset=dataset.drop(columns=["Project_ID"], axis=1)
dataset

,Industry,Agent_Type,Primary_Tool,Status,Failure_Reason,Human_in_the_Loop_Ratio,Tokens_per_Task,ROI_Score
0,Insurance,Autonomous,LangGraph,Production,NaN,0.389,2094,2.51
1,Retail,Assistant,CrewAI,Production,NaN,0.990,5993,3.78
2,Energy,Multi-agent Swarm,AutoGPT 3.0,Pilot,Loop Error,0.475,9032,0.91
3,Technology,Multi-agent Swarm,LangGraph,Pilot,Loop Error,0.372,8735,0.75
4,Finance,Autonomous,LangGraph,Production,NaN,0.613,1645,2.58
...,...,...,...,...,...,...,...,...
2495,Manufacturing,Autonomous,CrewAI,Pilot,Loop Error,0.266,5788,-0.14
2496,Manufacturing,Autonomous,LangGraph,Pilot,Schema Drift,0.162,3609,1.73
2497,Healthcare,Assistant,CrewAI,Pilot,Security Violation,0.799,3182,0.63
2498,Energy,Assistant,CrewAI,Pilot,Loop Error,0.571,5360,-0.28
2499,Manufacturing,Assistant,LangGraph,Pilot,Loop Error,0.928,2814,-0.20

In [15]:
dataset['Industry'].name

'Industry'

In [13]:
print(dataset['Failure_Reason'].value_counts())
print('-----------------------------')
print(dataset['Agent_Type'].value_counts())
print('-----------------------------')
print(dataset['Primary_Tool'].value_counts())
print('-----------------------------')
print(dataset['Status'].value_counts())

Failure_Reason
Loop Error            713
Cost Overrun          576
Schema Drift          439
Security Violation    426
No Failure            346
Name: count, dtype: int64
-----------------------------
Agent_Type
Assistant            988
Autonomous           918
Multi-agent Swarm    594
Name: count, dtype: int64
-----------------------------
Primary_Tool
LangGraph      1059
CrewAI          851
AutoGPT 3.0     590
Name: count, dtype: int64
-----------------------------
Status
Pilot         1267
Abandoned      887
Production     346
Name: count, dtype: int64

In [14]:
print(dataset['Industry'].value_counts())

Industry
Finance          410
Technology       345
Healthcare       329
Retail           318
Manufacturing    217
Government       199
Insurance        190
Legal            184
Energy           155
Telecom          153
Name: count, dtype: int64

In [6]:
dataset["Failure_Reason"].fillna("No Failure", inplace=True)

In [7]:
dataset.isnull().sum()

Industry                   0
Agent_Type                 0
Primary_Tool               0
Status                     0
Failure_Reason             0
Human_in_the_Loop_Ratio    0
Tokens_per_Task            0
ROI_Score                  0
dtype: int64

In [86]:
unique_indus=dataset["Industry"].unique()
print(unique_indus)
unique_Agent=dataset["Agent_Type"].unique()
print(unique_Agent)
unique_Tool=dataset["Primary_Tool"].unique()
print(unique_Tool)
unique_Status=dataset["Status"].unique()
print(unique_Status)
unique_Failure=dataset["Failure_Reason"].unique()
print(unique_Failure)

['Insurance' 'Retail' 'Energy' 'Technology' 'Finance' 'Telecom'
 'Government' 'Healthcare' 'Manufacturing' 'Legal']
['Autonomous' 'Assistant' 'Multi-agent Swarm']
['LangGraph' 'CrewAI' 'AutoGPT 3.0']
['Production' 'Pilot' 'Abandoned']
['No Failure' 'Loop Error' 'Schema Drift' 'Cost Overrun'
 'Security Violation']

In [87]:
dataset.describe()

       Human_in_the_Loop_Ratio  Tokens_per_Task    ROI_Score
count              2500.000000      2500.000000  2500.000000
mean                  0.484933      5148.214800     0.425728
std                   0.271753      2473.059822     1.272453
min                   0.010000       500.000000    -2.000000
25%                   0.239750      3491.000000    -0.470000
50%                   0.483000      4655.500000     0.160000
75%                   0.724000      6322.500000     1.060000
max                   0.990000     20155.000000     5.000000

In [88]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Industry                 2500 non-null   object
 1   Agent_Type               2500 non-null   object
 2   Primary_Tool             2500 non-null   object
 3   Status                   2500 non-null   object
 4   Failure_Reason           2500 non-null   object
 5   Human_in_the_Loop_Ratio  2500 non-null   float64
 6   Tokens_per_Task          2500 non-null   int64
 7   ROI_Score                2500 non-null   float64
dtypes: float64(2), int64(1), object(5)
memory usage: 156.4+ KB

In [89]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Industry                 2500 non-null   object
 1   Agent_Type               2500 non-null   object
 2   Primary_Tool             2500 non-null   object
 3   Status                   2500 non-null   object
 4   Failure_Reason           2500 non-null   object
 5   Human_in_the_Loop_Ratio  2500 non-null   float64
 6   Tokens_per_Task          2500 non-null   int64
 7   ROI_Score                2500 non-null   float64
dtypes: float64(2), int64(1), object(5)
memory usage: 156.4+ KB

In [16]:
dataset

,Industry,Agent_Type,Primary_Tool,Status,Failure_Reason,Human_in_the_Loop_Ratio,Tokens_per_Task,ROI_Score
0,Insurance,Autonomous,LangGraph,Production,No Failure,0.389,2094,2.51
1,Retail,Assistant,CrewAI,Production,No Failure,0.990,5993,3.78
2,Energy,Multi-agent Swarm,AutoGPT 3.0,Pilot,Loop Error,0.475,9032,0.91
3,Technology,Multi-agent Swarm,LangGraph,Pilot,Loop Error,0.372,8735,0.75
4,Finance,Autonomous,LangGraph,Production,No Failure,0.613,1645,2.58
...,...,...,...,...,...,...,...,...
2495,Manufacturing,Autonomous,CrewAI,Pilot,Loop Error,0.266,5788,-0.14
2496,Manufacturing,Autonomous,LangGraph,Pilot,Schema Drift,0.162,3609,1.73
2497,Healthcare,Assistant,CrewAI,Pilot,Security Violation,0.799,3182,0.63
2498,Energy,Assistant,CrewAI,Pilot,Loop Error,0.571,5360,-0.28
2499,Manufacturing,Assistant,LangGraph,Pilot,Loop Error,0.928,2814,-0.20

We can do the label encoding by a new function of the pandas "get_dummies". Just pass all the categorical columns and it will convert each by label encoding.

In [91]:
# dataset = pd.get_dummies(dataset, columns=["Industry", "Agent_Type", "Primary_Tool", "Status", "Failure_Reason"], drop_first=True)

In [19]:
encoder = OneHotEncoder(sparse_output=False)

one_hot_encoded = encoder.fit_transform(dataset[dataset.columns[dataset.dtypes == "object"]])

one_hot_df = pd.DataFrame(one_hot_encoded, 
                          columns=encoder.get_feature_names_out(dataset.columns[dataset.dtypes == "object"]))

dataset= pd.concat([dataset.drop(dataset.columns[dataset.dtypes == "object"], axis=1), one_hot_df], axis=1)

In [20]:
dataset

,Human_in_the_Loop_Ratio,Tokens_per_Task,ROI_Score,Industry_Energy,Industry_Finance,Industry_Government,Industry_Healthcare,Industry_Insurance,Industry_Legal,Industry_Manufacturing,...,Primary_Tool_CrewAI,Primary_Tool_LangGraph,Status_Abandoned,Status_Pilot,Status_Production,Failure_Reason_Cost Overrun,Failure_Reason_Loop Error,Failure_Reason_No Failure,Failure_Reason_Schema Drift,Failure_Reason_Security Violation
0,0.389,2094,2.51,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
1,0.990,5993,3.78,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
2,0.475,9032,0.91,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
3,0.372,8735,0.75,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
4,0.613,1645,2.58,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,0.266,5788,-0.14,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
2496,0.162,3609,1.73,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
2497,0.799,3182,0.63,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
2498,0.571,5360,-0.28,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
2499,0.928,2814,-0.20,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0

In [94]:
# dataset["Industry"] = dataset["Industry"].map({ key:index for index,key in enumerate(unique_indus)})
# dataset["Agent_Type"] = dataset["Agent_Type"].map({ key:index for index,key in enumerate(unique_Agent)})
# dataset["Primary_Tool"] = dataset["Primary_Tool"].map({ key:index for index,key in enumerate(unique_Tool)})
# dataset["Status"] = dataset["Status"].map({ key:index for index,key in enumerate(unique_Status)})
# dataset["Failure_Reason"] = dataset["Failure_Reason"].map({ key:index for index,key in enumerate(unique_Failure)})

In [95]:
dataset

,Human_in_the_Loop_Ratio,Tokens_per_Task,ROI_Score,Industry_Energy,Industry_Finance,Industry_Government,Industry_Healthcare,Industry_Insurance,Industry_Legal,Industry_Manufacturing,...,Primary_Tool_CrewAI,Primary_Tool_LangGraph,Status_Abandoned,Status_Pilot,Status_Production,Failure_Reason_Cost Overrun,Failure_Reason_Loop Error,Failure_Reason_No Failure,Failure_Reason_Schema Drift,Failure_Reason_Security Violation
0,0.389,2094,2.51,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
1,0.990,5993,3.78,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
2,0.475,9032,0.91,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
3,0.372,8735,0.75,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
4,0.613,1645,2.58,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,0.266,5788,-0.14,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
2496,0.162,3609,1.73,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
2497,0.799,3182,0.63,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
2498,0.571,5360,-0.28,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
2499,0.928,2814,-0.20,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0

In [96]:
x_train, x_test, y_train, y_test = train_test_split(dataset.drop(columns=["ROI_Score"], axis=1), dataset["ROI_Score"], test_size=0.2, random_state=42)
x_train.to_csv(r"D:\End to end project\Learning_MLOps\data_save\x_train.csv", index=False)
x_test.to_csv(r"D:\End to end project\Learning_MLOps\data_save\x_test.csv", index=False)
y_train.to_csv(r"D:\End to end project\Learning_MLOps\data_save\y_train.csv", index=False)
y_test.to_csv(r"D:\End to end project\Learning_MLOps\data_save\y_test.csv", index=False)

In [97]:
scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)

# Here we use a new library named Optuna which is use for finding the best Model and its best Hyperparameters. We Have to define a objective funtion and in that function we declare all our candidate models and there repective hyperparameters.

In [98]:
def objective0(trial):
    regressor=trial.suggest_categorical("regressor", ["RandomForestRegressor", "XGBRegressor"])
    
    if regressor=="RandomForestRegressor":
        n_estimators=trial.suggest_int("n_estimators", 10, 200)
        max_depth=trial.suggest_int("max_depth", 5, 10)
        min_samples_split=trial.suggest_int("min_samples_split", 2, 10)
        min_samples_leaf=trial.suggest_int("min_samples_leaf", 1, 10)
        
        model=RandomForestRegressor(n_estimators=n_estimators, max_depth=max_depth, random_state=42, min_samples_split=min_samples_split, min_samples_leaf=min_samples_leaf)
    elif regressor=="XGBRegressor":
        n_estimators=trial.suggest_int("n_estimators", 10, 200)
        max_depth=trial.suggest_int("max_depth", 2, 10)
        learning_rate=trial.suggest_float("learning_rate", 0.01, 0.03)
        
        model=XGBRegressor(n_estimators=n_estimators, max_depth=max_depth, learning_rate=learning_rate, random_state=42)

    

    score=cross_val_score(model, x_train, y_train, cv=5, scoring="r2").mean()
    return score

In [99]:
def objective1(trial):
    regressor=trial.suggest_categorical("regressor", ["ElasticNet", "SVR", "KNN"])
    if regressor=="ElasticNet":
        alpha=trial.suggest_float("alpha", 0.001, 10.0)
        l1_ratio=trial.suggest_float("l1_ratio", 0.0, 1.0)
        
        model=ElasticNet(alpha=alpha, l1_ratio=l1_ratio, random_state=42)
    elif regressor=="SVR":
        C=trial.suggest_float("C", 0.1, 10.0)
        gamma=trial.suggest_float("gamma", 0.001, 0.01)
        
        model=SVR(C=C, gamma=gamma)
    elif regressor=="KNN":
        n_neighbors=trial.suggest_int("n_neighbors", 1, 30)
        model=KNN(n_neighbors=n_neighbors)

    
    score=cross_val_score(model, x_train_scaled, y_train, cv=5, scoring="r2").mean()
    return score

In [100]:
study0=opt.create_study(direction="maximize")
study0.optimize(objective0, n_trials=100)

[I 2026-04-29 15:20:06,319] A new study created in memory with name: no-name-89896b26-1577-4e03-a294-01a1e8c4bd44

[I 2026-04-29 15:20:06,666] Trial 0 finished with value: 0.3681297046639284 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 21, 'max_depth': 10, 'learning_rate': 0.017960692876459242}. Best is trial 0 with value: 0.3681297046639284.
[I 2026-04-29 15:20:06,977] Trial 1 finished with value: 0.7087064142944282 and parameters: {'regressor': 'RandomForestRegressor', 'n_estimators': 20, 'max_depth': 5, 'min_samples_split': 4, 'min_samples_leaf': 4}. Best is trial 1 with value: 0.7087064142944282.
[I 2026-04-29 15:20:07,190] Trial 2 finished with value: 0.32457866826021686 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 25, 'max_depth': 7, 'learning_rate': 0.012378730282475839}. Best is trial 1 with value: 0.7087064142944282.
[I 2026-04-29 15:20:07,717] Trial 3 finished with value: 0.6966804824803281 and parameters: {'regressor': 'RandomForestRegressor', 'n_estimators': 17, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 4}. Best is trial 1 with value: 0.7087064142944282.
[I 2026-04-29 15:20:10,346] Trial 4 finished with value: 0.7043003964259041 and parameters: {'regressor': 'RandomForestRegressor', 'n_estimators': 118, 'max_depth': 8, 'min_samples_split': 9, 'min_samples_leaf': 6}. Best is trial 1 with value: 0.7087064142944282.
[I 2026-04-29 15:20:14,088] Trial 5 finished with value: 0.7040571056192121 and parameters: {'regressor': 'RandomForestRegressor', 'n_estimators': 155, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 3}. Best is trial 1 with value: 0.7087064142944282.
[I 2026-04-29 15:20:17,407] Trial 6 finished with value: 0.7033248722255399 and parameters: {'regressor': 'RandomForestRegressor', 'n_estimators': 138, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 9}. Best is trial 1 with value: 0.7087064142944282.
[I 2026-04-29 15:20:17,571] Trial 7 finished with value: 0.3156659878865943 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 15, 'max_depth': 5, 'learning_rate': 0.01965504305727107}. Best is trial 1 with value: 0.7087064142944282.
[I 2026-04-29 15:20:17,940] Trial 8 finished with value: 0.7108499434103358 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 115, 'max_depth': 3, 'learning_rate': 0.027372139412255345}. Best is trial 8 with value: 0.7108499434103358.
[I 2026-04-29 15:20:20,835] Trial 9 finished with value: 0.6987861810208086 and parameters: {'regressor': 'RandomForestRegressor', 'n_estimators': 106, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 3}. Best is trial 8 with value: 0.7108499434103358.
[I 2026-04-29 15:20:21,245] Trial 10 finished with value: 0.7113608196470665 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 191, 'max_depth': 2, 'learning_rate': 0.028886761508579925}. Best is trial 10 with value: 0.7113608196470665.
[I 2026-04-29 15:20:21,681] Trial 11 finished with value: 0.7112033843388089 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 200, 'max_depth': 2, 'learning_rate': 0.029896927483675707}. Best is trial 10 with value: 0.7113608196470665.
[I 2026-04-29 15:20:22,091] Trial 12 finished with value: 0.7113594941069122 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 194, 'max_depth': 2, 'learning_rate': 0.02971224294722218}. Best is trial 10 with value: 0.7113608196470665.
[I 2026-04-29 15:20:22,592] Trial 13 finished with value: 0.7105221529842555 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 200, 'max_depth': 3, 'learning_rate': 0.025572636545993854}. Best is trial 10 with value: 0.7113608196470665.
[I 2026-04-29 15:20:22,981] Trial 14 finished with value: 0.711527879362247 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 173, 'max_depth': 2, 'learning_rate': 0.02437225680413011}. Best is trial 14 with value: 0.711527879362247.
[I 2026-04-29 15:20:23,496] Trial 15 finished with value: 0.7078120806611554 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 165, 'max_depth': 4, 'learning_rate': 0.024992321479315637}. Best is trial 14 with value: 0.711527879362247.
[I 2026-04-29 15:20:23,785] Trial 16 finished with value: 0.6922474614416139 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 80, 'max_depth': 4, 'learning_rate': 0.022483073243013945}. Best is trial 14 with value: 0.711527879362247.
[I 2026-04-29 15:20:24,174] Trial 17 finished with value: 0.7113515373994367 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 169, 'max_depth': 2, 'learning_rate': 0.022884406751843608}. Best is trial 14 with value: 0.711527879362247.
[I 2026-04-29 15:20:24,551] Trial 18 finished with value: 0.6350711052120623 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 71, 'max_depth': 6, 'learning_rate': 0.016422258305995887}. Best is trial 14 with value: 0.711527879362247.
[I 2026-04-29 15:20:25,016] Trial 19 finished with value: 0.7107880522540592 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 178, 'max_depth': 3, 'learning_rate': 0.027162797299446685}. Best is trial 14 with value: 0.711527879362247.
[I 2026-04-29 15:20:25,461] Trial 20 finished with value: 0.708427360687763 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 139, 'max_depth': 4, 'learning_rate': 0.022407132225579395}. Best is trial 14 with value: 0.711527879362247.
[I 2026-04-29 15:20:25,870] Trial 21 finished with value: 0.7114320859346237 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 183, 'max_depth': 2, 'learning_rate': 0.029389915584850906}. Best is trial 14 with value: 0.711527879362247.
[I 2026-04-29 15:20:26,271] Trial 22 finished with value: 0.7113995255338159 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 185, 'max_depth': 2, 'learning_rate': 0.027709084890547693}. Best is trial 14 with value: 0.711527879362247.
[I 2026-04-29 15:20:26,677] Trial 23 finished with value: 0.7110915092902294 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 151, 'max_depth': 3, 'learning_rate': 0.024835022793052625}. Best is trial 14 with value: 0.711527879362247.
[I 2026-04-29 15:20:27,074] Trial 24 finished with value: 0.7115131009424973 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 181, 'max_depth': 2, 'learning_rate': 0.02792891714730601}. Best is trial 14 with value: 0.711527879362247.
[I 2026-04-29 15:20:27,781] Trial 25 finished with value: 0.699821623692743 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 174, 'max_depth': 5, 'learning_rate': 0.026023925506614486}. Best is trial 14 with value: 0.711527879362247.
[I 2026-04-29 15:20:28,161] Trial 26 finished with value: 0.710820795318617 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 133, 'max_depth': 3, 'learning_rate': 0.023625788939038404}. Best is trial 14 with value: 0.711527879362247.
[I 2026-04-29 15:20:28,649] Trial 27 finished with value: 0.707899852139195 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 158, 'max_depth': 4, 'learning_rate': 0.027605959358145565}. Best is trial 14 with value: 0.711527879362247.
[I 2026-04-29 15:20:28,860] Trial 28 finished with value: 0.6553084415298173 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 69, 'max_depth': 2, 'learning_rate': 0.020518046378223097}. Best is trial 14 with value: 0.711527879362247.
[I 2026-04-29 15:20:29,711] Trial 29 finished with value: 0.6894857944841484 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 183, 'max_depth': 6, 'learning_rate': 0.028475501813226667}. Best is trial 14 with value: 0.711527879362247.
[I 2026-04-29 15:20:30,117] Trial 30 finished with value: 0.7110990351563913 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 149, 'max_depth': 3, 'learning_rate': 0.02642536172533871}. Best is trial 14 with value: 0.711527879362247.
[I 2026-04-29 15:20:30,513] Trial 31 finished with value: 0.7114089939007912 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 184, 'max_depth': 2, 'learning_rate': 0.028341171804623647}. Best is trial 14 with value: 0.711527879362247.
[I 2026-04-29 15:20:30,889] Trial 32 finished with value: 0.7115045795818855 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 172, 'max_depth': 2, 'learning_rate': 0.029821112546109394}. Best is trial 14 with value: 0.711527879362247.
[I 2026-04-29 15:20:31,338] Trial 33 finished with value: 0.7104567420223866 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 170, 'max_depth': 3, 'learning_rate': 0.02986287147383581}. Best is trial 14 with value: 0.711527879362247.
[I 2026-04-29 15:20:34,652] Trial 34 finished with value: 0.7065031159034436 and parameters: {'regressor': 'RandomForestRegressor', 'n_estimators': 161, 'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 10}. Best is trial 14 with value: 0.711527879362247.
[I 2026-04-29 15:20:34,798] Trial 35 finished with value: 0.6072193400184054 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 39, 'max_depth': 2, 'learning_rate': 0.026483500935310954}. Best is trial 14 with value: 0.711527879362247.
[I 2026-04-29 15:20:37,847] Trial 36 finished with value: 0.7030969204535306 and parameters: {'regressor': 'RandomForestRegressor', 'n_estimators': 127, 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 1}. Best is trial 14 with value: 0.711527879362247.
[I 2026-04-29 15:20:38,349] Trial 37 finished with value: 0.7085178752574233 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 144, 'max_depth': 4, 'learning_rate': 0.024206211856407176}. Best is trial 14 with value: 0.711527879362247.
[I 2026-04-29 15:20:42,286] Trial 38 finished with value: 0.70246546124595 and parameters: {'regressor': 'RandomForestRegressor', 'n_estimators': 176, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 7}. Best is trial 14 with value: 0.711527879362247.
[I 2026-04-29 15:20:42,692] Trial 39 finished with value: 0.7106072295283875 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 159, 'max_depth': 3, 'learning_rate': 0.028747838121246705}. Best is trial 14 with value: 0.711527879362247.
[I 2026-04-29 15:20:42,944] Trial 40 finished with value: 0.6878054384549489 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 93, 'max_depth': 2, 'learning_rate': 0.020795596223436998}. Best is trial 14 with value: 0.711527879362247.
[I 2026-04-29 15:20:43,372] Trial 41 finished with value: 0.7114695712782904 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 185, 'max_depth': 2, 'learning_rate': 0.028688303155140767}. Best is trial 14 with value: 0.711527879362247.
[I 2026-04-29 15:20:43,789] Trial 42 finished with value: 0.7024095950143229 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 190, 'max_depth': 2, 'learning_rate': 0.013125353449451926}. Best is trial 14 with value: 0.711527879362247.
[I 2026-04-29 15:20:44,339] Trial 43 finished with value: 0.7105719206218882 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 176, 'max_depth': 3, 'learning_rate': 0.029919230712174612}. Best is trial 14 with value: 0.711527879362247.
[I 2026-04-29 15:20:44,798] Trial 44 finished with value: 0.7116017395840822 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 167, 'max_depth': 2, 'learning_rate': 0.02684913381713073}. Best is trial 44 with value: 0.7116017395840822.
[I 2026-04-29 15:20:48,677] Trial 45 finished with value: 0.7032496798146851 and parameters: {'regressor': 'RandomForestRegressor', 'n_estimators': 166, 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 8}. Best is trial 44 with value: 0.7116017395840822.
[I 2026-04-29 15:20:49,215] Trial 46 finished with value: 0.7105589484092036 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 194, 'max_depth': 3, 'learning_rate': 0.026884682791699234}. Best is trial 44 with value: 0.7116017395840822.
[I 2026-04-29 15:20:49,898] Trial 47 finished with value: 0.7002391443984003 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 147, 'max_depth': 5, 'learning_rate': 0.017212181591189767}. Best is trial 44 with value: 0.7116017395840822.
[I 2026-04-29 15:20:50,385] Trial 48 finished with value: 0.7114288897621595 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 198, 'max_depth': 2, 'learning_rate': 0.02795604637120865}. Best is trial 44 with value: 0.7116017395840822.
[I 2026-04-29 15:20:53,954] Trial 49 finished with value: 0.6980960906398053 and parameters: {'regressor': 'RandomForestRegressor', 'n_estimators': 121, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 1}. Best is trial 44 with value: 0.7116017395840822.
[I 2026-04-29 15:20:54,519] Trial 50 finished with value: 0.7114558749065184 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 154, 'max_depth': 2, 'learning_rate': 0.02557681852028862}. Best is trial 44 with value: 0.7116017395840822.
[I 2026-04-29 15:20:54,870] Trial 51 finished with value: 0.7114768749528035 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 156, 'max_depth': 2, 'learning_rate': 0.0257119905182178}. Best is trial 44 with value: 0.7116017395840822.
[I 2026-04-29 15:20:55,287] Trial 52 finished with value: 0.7114934024892234 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 165, 'max_depth': 2, 'learning_rate': 0.028720798514767762}. Best is trial 44 with value: 0.7116017395840822.
[I 2026-04-29 15:20:55,772] Trial 53 finished with value: 0.710748851103199 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 166, 'max_depth': 3, 'learning_rate': 0.02735644346313036}. Best is trial 44 with value: 0.7116017395840822.
[I 2026-04-29 15:20:56,136] Trial 54 finished with value: 0.7107624204324954 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 143, 'max_depth': 2, 'learning_rate': 0.025055578295252443}. Best is trial 44 with value: 0.7116017395840822.
[I 2026-04-29 15:20:56,598] Trial 55 finished with value: 0.7086315864350006 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 134, 'max_depth': 4, 'learning_rate': 0.026300536001032535}. Best is trial 44 with value: 0.7116017395840822.
[I 2026-04-29 15:20:57,002] Trial 56 finished with value: 0.7115180571243961 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 171, 'max_depth': 2, 'learning_rate': 0.023391863548264082}. Best is trial 44 with value: 0.7116017395840822.
[I 2026-04-29 15:20:57,463] Trial 57 finished with value: 0.7111697808664272 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 171, 'max_depth': 3, 'learning_rate': 0.023677759705147954}. Best is trial 44 with value: 0.7116017395840822.
[I 2026-04-29 15:20:57,878] Trial 58 finished with value: 0.7115572521139402 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 190, 'max_depth': 2, 'learning_rate': 0.021753542470832384}. Best is trial 44 with value: 0.7116017395840822.
[I 2026-04-29 15:20:58,343] Trial 59 finished with value: 0.7110822273730445 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 179, 'max_depth': 3, 'learning_rate': 0.01919528906691719}. Best is trial 44 with value: 0.7116017395840822.
[I 2026-04-29 15:20:58,764] Trial 60 finished with value: 0.7115444406212488 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 192, 'max_depth': 2, 'learning_rate': 0.021850201450162966}. Best is trial 44 with value: 0.7116017395840822.
[I 2026-04-29 15:20:59,172] Trial 61 finished with value: 0.7115913625875958 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 191, 'max_depth': 2, 'learning_rate': 0.02160852461110291}. Best is trial 44 with value: 0.7116017395840822.
[I 2026-04-29 15:20:59,573] Trial 62 finished with value: 0.7116111332965102 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 191, 'max_depth': 2, 'learning_rate': 0.021558816631401325}. Best is trial 62 with value: 0.7116111332965102.
[I 2026-04-29 15:20:59,995] Trial 63 finished with value: 0.7115274351505507 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 189, 'max_depth': 2, 'learning_rate': 0.021444261595161072}. Best is trial 62 with value: 0.7116111332965102.
[I 2026-04-29 15:21:00,488] Trial 64 finished with value: 0.7110359927854939 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 192, 'max_depth': 3, 'learning_rate': 0.021593274889921663}. Best is trial 62 with value: 0.7116111332965102.
[I 2026-04-29 15:21:00,905] Trial 65 finished with value: 0.7115636612192988 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 191, 'max_depth': 2, 'learning_rate': 0.02200388312928984}. Best is trial 62 with value: 0.7116111332965102.
[I 2026-04-29 15:21:01,420] Trial 66 finished with value: 0.7111987785534544 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 199, 'max_depth': 3, 'learning_rate': 0.018970130462616863}. Best is trial 62 with value: 0.7116111332965102.
[I 2026-04-29 15:21:01,832] Trial 67 finished with value: 0.7115857166095756 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 188, 'max_depth': 2, 'learning_rate': 0.022221569060101098}. Best is trial 62 with value: 0.7116111332965102.
[I 2026-04-29 15:21:02,254] Trial 68 finished with value: 0.711539142458357 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 195, 'max_depth': 2, 'learning_rate': 0.021995102148798934}. Best is trial 62 with value: 0.7116111332965102.
[I 2026-04-29 15:21:02,772] Trial 69 finished with value: 0.7111851961807 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 200, 'max_depth': 3, 'learning_rate': 0.019907555191609163}. Best is trial 62 with value: 0.7116111332965102.
[I 2026-04-29 15:21:06,771] Trial 70 finished with value: 0.7050423090189419 and parameters: {'regressor': 'RandomForestRegressor', 'n_estimators': 186, 'max_depth': 8, 'min_samples_split': 10, 'min_samples_leaf': 10}. Best is trial 62 with value: 0.7116111332965102.
[I 2026-04-29 15:21:07,196] Trial 71 finished with value: 0.7115907455113971 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 194, 'max_depth': 2, 'learning_rate': 0.02192892343544747}. Best is trial 62 with value: 0.7116111332965102.
[I 2026-04-29 15:21:07,597] Trial 72 finished with value: 0.7116162920778639 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 186, 'max_depth': 2, 'learning_rate': 0.02265998278153283}. Best is trial 72 with value: 0.7116162920778639.
[I 2026-04-29 15:21:07,993] Trial 73 finished with value: 0.7115452531992766 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 180, 'max_depth': 2, 'learning_rate': 0.022940933187235737}. Best is trial 72 with value: 0.7116162920778639.
[I 2026-04-29 15:21:08,461] Trial 74 finished with value: 0.7114924881606978 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 189, 'max_depth': 2, 'learning_rate': 0.020846359714569}. Best is trial 72 with value: 0.7116162920778639.
[I 2026-04-29 15:21:08,852] Trial 75 finished with value: 0.7115900313966397 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 180, 'max_depth': 2, 'learning_rate': 0.022888577227792785}. Best is trial 72 with value: 0.7116162920778639.
[I 2026-04-29 15:21:09,881] Trial 76 finished with value: 0.6858514455888505 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 180, 'max_depth': 7, 'learning_rate': 0.022661110909890793}. Best is trial 72 with value: 0.7116162920778639.
[I 2026-04-29 15:21:10,081] Trial 77 finished with value: 0.5712771805079645 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 44, 'max_depth': 3, 'learning_rate': 0.01827182047024592}. Best is trial 72 with value: 0.7116162920778639.
[I 2026-04-29 15:21:10,496] Trial 78 finished with value: 0.7115284965340523 and parameters: {'regressor': 'XGBRegressor', 'n_estimators': 195, 'max_depth': 2, 'learning_rate': 0.0205758853733662}. Best is trial 72 with value: 0.7116162920778639.

In [101]:
print(study0.best_trial.params)
print(study0.best_trial.value)

{'regressor': 'XGBRegressor', 'n_estimators': 187, 'max_depth': 2, 'learning_rate': 0.022294413883118733}
0.711617456354529

In [102]:
study1=opt.create_study(direction="maximize")
study1.optimize(objective1, n_trials=100)

[I 2026-04-29 15:21:25,367] A new study created in memory with name: no-name-86eef39b-6b70-4707-89cb-aec0a64d5876
[I 2026-04-29 15:21:25,408] Trial 0 finished with value: 0.6718024371512478 and parameters: {'regressor': 'ElasticNet', 'alpha': 0.18849029935014133, 'l1_ratio': 0.6788200393744057}. Best is trial 0 with value: 0.6718024371512478.
[I 2026-04-29 15:21:25,436] Trial 1 finished with value: 0.39374487248613355 and parameters: {'regressor': 'ElasticNet', 'alpha': 1.2321595043609774, 'l1_ratio': 0.35126096241239435}. Best is trial 0 with value: 0.6718024371512478.
[I 2026-04-29 15:21:25,639] Trial 2 finished with value: 0.6313608478349576 and parameters: {'regressor': 'KNN', 'n_neighbors': 11}. Best is trial 0 with value: 0.6718024371512478.
[I 2026-04-29 15:21:26,717] Trial 3 finished with value: 0.6747486688365607 and parameters: {'regressor': 'SVR', 'C': 9.730047313501338, 'gamma': 0.009296052994117038}. Best is trial 3 with value: 0.6747486688365607.
[I 2026-04-29 15:21:27,704] Trial 4 finished with value: 0.6791923462874168 and parameters: {'regressor': 'SVR', 'C': 8.636445458073416, 'gamma': 0.007732166758862221}. Best is trial 4 with value: 0.6791923462874168.
[I 2026-04-29 15:21:28,524] Trial 5 finished with value: 0.6394548008457 and parameters: {'regressor': 'SVR', 'C': 0.30720020492330774, 'gamma': 0.001322855626826016}. Best is trial 4 with value: 0.6791923462874168.
[I 2026-04-29 15:21:28,692] Trial 6 finished with value: 0.6271144962179609 and parameters: {'regressor': 'KNN', 'n_neighbors': 10}. Best is trial 4 with value: 0.6791923462874168.
[I 2026-04-29 15:21:29,617] Trial 7 finished with value: 0.6841563768254668 and parameters: {'regressor': 'SVR', 'C': 6.315135658470083, 'gamma': 0.006585668676704596}. Best is trial 7 with value: 0.6841563768254668.
[I 2026-04-29 15:21:29,739] Trial 8 finished with value: 0.6145710892493426 and parameters: {'regressor': 'KNN', 'n_neighbors': 8}. Best is trial 7 with value: 0.6841563768254668.
[I 2026-04-29 15:21:29,758] Trial 9 finished with value: -0.0005472004134360109 and parameters: {'regressor': 'ElasticNet', 'alpha': 5.9361361393289656, 'l1_ratio': 0.8609497332430968}. Best is trial 7 with value: 0.6841563768254668.
[I 2026-04-29 15:21:30,550] Trial 10 finished with value: 0.6925302429405347 and parameters: {'regressor': 'SVR', 'C': 4.186013981844701, 'gamma': 0.00453003090275762}. Best is trial 10 with value: 0.6925302429405347.
[I 2026-04-29 15:21:31,339] Trial 11 finished with value: 0.6924366368515182 and parameters: {'regressor': 'SVR', 'C': 4.601826994158148, 'gamma': 0.004369297159286264}. Best is trial 10 with value: 0.6925302429405347.
[I 2026-04-29 15:21:32,134] Trial 12 finished with value: 0.6959855781798957 and parameters: {'regressor': 'SVR', 'C': 3.3929847365602495, 'gamma': 0.0035801281158742075}. Best is trial 12 with value: 0.6959855781798957.
[I 2026-04-29 15:21:32,939] Trial 13 finished with value: 0.6960184052957888 and parameters: {'regressor': 'SVR', 'C': 3.3763805176600235, 'gamma': 0.003580569981512945}. Best is trial 13 with value: 0.6960184052957888.
[I 2026-04-29 15:21:33,741] Trial 14 finished with value: 0.6978539924426619 and parameters: {'regressor': 'SVR', 'C': 1.651312706705912, 'gamma': 0.0021362942876912558}. Best is trial 14 with value: 0.6978539924426619.
[I 2026-04-29 15:21:34,621] Trial 15 finished with value: 0.6923259668004823 and parameters: {'regressor': 'SVR', 'C': 0.9433284797840648, 'gamma': 0.0015291759744822707}. Best is trial 14 with value: 0.6978539924426619.
[I 2026-04-29 15:21:35,419] Trial 16 finished with value: 0.6979949895529576 and parameters: {'regressor': 'SVR', 'C': 2.500063866418941, 'gamma': 0.00282561715926591}. Best is trial 16 with value: 0.6979949895529576.
[I 2026-04-29 15:21:36,169] Trial 17 finished with value: 0.6983753426891595 and parameters: {'regressor': 'SVR', 'C': 1.989811792127094, 'gamma': 0.0027131222155412477}. Best is trial 17 with value: 0.6983753426891595.
[I 2026-04-29 15:21:36,192] Trial 18 finished with value: 0.017768046522392122 and parameters: {'regressor': 'ElasticNet', 'alpha': 9.847926563596832, 'l1_ratio': 0.08299406416922434}. Best is trial 17 with value: 0.6983753426891595.
[I 2026-04-29 15:21:36,336] Trial 19 finished with value: 0.6372377628474352 and parameters: {'regressor': 'KNN', 'n_neighbors': 30}. Best is trial 17 with value: 0.6983753426891595.
[I 2026-04-29 15:21:37,060] Trial 20 finished with value: 0.6983574134313104 and parameters: {'regressor': 'SVR', 'C': 2.1730649327398535, 'gamma': 0.0026562852211247847}. Best is trial 17 with value: 0.6983753426891595.
[I 2026-04-29 15:21:37,842] Trial 21 finished with value: 0.6983628842407855 and parameters: {'regressor': 'SVR', 'C': 1.9146608993636154, 'gamma': 0.0027380672940255724}. Best is trial 17 with value: 0.6983753426891595.
[I 2026-04-29 15:21:38,651] Trial 22 finished with value: 0.6941828547998343 and parameters: {'regressor': 'SVR', 'C': 2.0617602974588025, 'gamma': 0.005562071372015752}. Best is trial 17 with value: 0.6983753426891595.
[I 2026-04-29 15:21:39,403] Trial 23 finished with value: 0.6982196202354582 and parameters: {'regressor': 'SVR', 'C': 2.2630505486150576, 'gamma': 0.0027430329794750708}. Best is trial 17 with value: 0.6983753426891595.
[I 2026-04-29 15:21:40,191] Trial 24 finished with value: 0.6956724856834876 and parameters: {'regressor': 'SVR', 'C': 5.438420616933751, 'gamma': 0.00291040700814077}. Best is trial 17 with value: 0.6983753426891595.
[I 2026-04-29 15:21:40,913] Trial 25 finished with value: 0.6837818264902873 and parameters: {'regressor': 'SVR', 'C': 0.25354298118094865, 'gamma': 0.004489085855763976}. Best is trial 17 with value: 0.6983753426891595.
[I 2026-04-29 15:21:41,672] Trial 26 finished with value: 0.6984817825407825 and parameters: {'regressor': 'SVR', 'C': 3.2348972199576025, 'gamma': 0.0013145455697541298}. Best is trial 26 with value: 0.6984817825407825.
[I 2026-04-29 15:21:42,424] Trial 27 finished with value: 0.6983552641812568 and parameters: {'regressor': 'SVR', 'C': 3.492291811253929, 'gamma': 0.0010446309808815235}. Best is trial 26 with value: 0.6984817825407825.
[I 2026-04-29 15:21:42,550] Trial 28 finished with value: 0.640862474265772 and parameters: {'regressor': 'KNN', 'n_neighbors': 25}. Best is trial 26 with value: 0.6984817825407825.
[I 2026-04-29 15:21:42,571] Trial 29 finished with value: -0.0005472004134360109 and parameters: {'regressor': 'ElasticNet', 'alpha': 5.2937468235415635, 'l1_ratio': 0.9727362771261732}. Best is trial 26 with value: 0.6984817825407825.
[I 2026-04-29 15:21:42,596] Trial 30 finished with value: -0.0005472004134360109 and parameters: {'regressor': 'ElasticNet', 'alpha': 9.944736433717267, 'l1_ratio': 0.357491173446083}. Best is trial 26 with value: 0.6984817825407825.
[I 2026-04-29 15:21:43,323] Trial 31 finished with value: 0.6979450702321031 and parameters: {'regressor': 'SVR', 'C': 1.6052517553096697, 'gamma': 0.0023152003569402117}. Best is trial 26 with value: 0.6984817825407825.
[I 2026-04-29 15:21:44,063] Trial 32 finished with value: 0.698591716524825 and parameters: {'regressor': 'SVR', 'C': 2.831159055381569, 'gamma': 0.0019361278314007089}. Best is trial 32 with value: 0.698591716524825.
[I 2026-04-29 15:21:44,842] Trial 33 finished with value: 0.6986057610548073 and parameters: {'regressor': 'SVR', 'C': 2.911516099270326, 'gamma': 0.001877156082279432}. Best is trial 33 with value: 0.6986057610548073.
[I 2026-04-29 15:21:45,597] Trial 34 finished with value: 0.698620351659619 and parameters: {'regressor': 'SVR', 'C': 3.0452157571323903, 'gamma': 0.0017640627580034068}. Best is trial 34 with value: 0.698620351659619.
[I 2026-04-29 15:21:46,410] Trial 35 finished with value: 0.6986660081119882 and parameters: {'regressor': 'SVR', 'C': 3.322813898034831, 'gamma': 0.001795570821305521}. Best is trial 35 with value: 0.6986660081119882.
[I 2026-04-29 15:21:47,233] Trial 36 finished with value: 0.6981035447584883 and parameters: {'regressor': 'SVR', 'C': 5.884754325183398, 'gamma': 0.0018550787724719807}. Best is trial 35 with value: 0.6986660081119882.
[I 2026-04-29 15:21:47,349] Trial 37 finished with value: 0.36389757843785153 and parameters: {'regressor': 'KNN', 'n_neighbors': 1}. Best is trial 35 with value: 0.6986660081119882.
[I 2026-04-29 15:21:47,373] Trial 38 finished with value: 0.4316439038253468 and parameters: {'regressor': 'ElasticNet', 'alpha': 2.93192664345826, 'l1_ratio': 0.027276083041662735}. Best is trial 35 with value: 0.6986660081119882.
[I 2026-04-29 15:21:48,127] Trial 39 finished with value: 0.6985841055386455 and parameters: {'regressor': 'SVR', 'C': 4.188150101334999, 'gamma': 0.001760546827903547}. Best is trial 35 with value: 0.6986660081119882.
[I 2026-04-29 15:21:48,861] Trial 40 finished with value: 0.6962188692867953 and parameters: {'regressor': 'SVR', 'C': 2.8337803776081962, 'gamma': 0.003817501512721553}. Best is trial 35 with value: 0.6986660081119882.
[I 2026-04-29 15:21:49,647] Trial 41 finished with value: 0.6984343883982607 and parameters: {'regressor': 'SVR', 'C': 3.9882700012798216, 'gamma': 0.0019402187464355506}. Best is trial 35 with value: 0.6986660081119882.
[I 2026-04-29 15:21:50,422] Trial 42 finished with value: 0.6988653396117673 and parameters: {'regressor': 'SVR', 'C': 4.825954637145253, 'gamma': 0.0010209547205192382}. Best is trial 42 with value: 0.6988653396117673.
[I 2026-04-29 15:21:51,170] Trial 43 finished with value: 0.6988558316371918 and parameters: {'regressor': 'SVR', 'C': 4.950928387502781, 'gamma': 0.0010641792426110473}. Best is trial 42 with value: 0.6988653396117673.
[I 2026-04-29 15:21:51,910] Trial 44 finished with value: 0.6989204300656705 and parameters: {'regressor': 'SVR', 'C': 6.924690050696126, 'gamma': 0.0011267986455312184}. Best is trial 44 with value: 0.6989204300656705.
[I 2026-04-29 15:21:52,653] Trial 45 finished with value: 0.6989601725207554 and parameters: {'regressor': 'SVR', 'C': 6.68853969386828, 'gamma': 0.001076031138304787}. Best is trial 45 with value: 0.6989601725207554.
[I 2026-04-29 15:21:52,795] Trial 46 finished with value: 0.6458922334782272 and parameters: {'regressor': 'KNN', 'n_neighbors': 20}. Best is trial 45 with value: 0.6989601725207554.
[I 2026-04-29 15:21:53,556] Trial 47 finished with value: 0.6989555521893858 and parameters: {'regressor': 'SVR', 'C': 7.196167203016431, 'gamma': 0.0010761445468520853}. Best is trial 45 with value: 0.6989601725207554.
[I 2026-04-29 15:21:54,540] Trial 48 finished with value: 0.6777703699716927 and parameters: {'regressor': 'SVR', 'C': 7.420402152128407, 'gamma': 0.009455973024524424}. Best is trial 45 with value: 0.6989601725207554.
[I 2026-04-29 15:21:55,329] Trial 49 finished with value: 0.6989640132524774 and parameters: {'regressor': 'SVR', 'C': 7.01217442351945, 'gamma': 0.001070419394758649}. Best is trial 49 with value: 0.6989640132524774.
[I 2026-04-29 15:21:55,358] Trial 50 finished with value: -0.0005472004134360109 and parameters: {'regressor': 'ElasticNet', 'alpha': 7.507570663744725, 'l1_ratio': 0.6071926898122767}. Best is trial 49 with value: 0.6989640132524774.
[I 2026-04-29 15:21:56,091] Trial 51 finished with value: 0.6989907491470608 and parameters: {'regressor': 'SVR', 'C': 7.015283273654784, 'gamma': 0.0010137226360850196}. Best is trial 51 with value: 0.6989907491470608.
[I 2026-04-29 15:21:56,824] Trial 52 finished with value: 0.6989612588152273 and parameters: {'regressor': 'SVR', 'C': 7.227210640992837, 'gamma': 0.001067500441724598}. Best is trial 51 with value: 0.6989907491470608.
[I 2026-04-29 15:21:57,763] Trial 53 finished with value: 0.682110214325111 and parameters: {'regressor': 'SVR', 'C': 7.2779535950528675, 'gamma': 0.006985695269192767}. Best is trial 51 with value: 0.6989907491470608.
[I 2026-04-29 15:21:58,684] Trial 54 finished with value: 0.6792654222040406 and parameters: {'regressor': 'SVR', 'C': 7.450540461063899, 'gamma': 0.008545231261393973}. Best is trial 51 with value: 0.6989907491470608.
[I 2026-04-29 15:21:59,439] Trial 55 finished with value: 0.6987529359948572 and parameters: {'regressor': 'SVR', 'C': 8.415514988748335, 'gamma': 0.0012681614333920573}. Best is trial 51 with value: 0.6989907491470608.
[I 2026-04-29 15:22:00,211] Trial 56 finished with value: 0.6986742811484201 and parameters: {'regressor': 'SVR', 'C': 6.665254925717954, 'gamma': 0.0013342533907981333}. Best is trial 51 with value: 0.6989907491470608.
[I 2026-04-29 15:22:01,002] Trial 57 finished with value: 0.6961494962156084 and parameters: {'regressor': 'SVR', 'C': 8.359425113688914, 'gamma': 0.0022544617350392}. Best is trial 51 with value: 0.6989907491470608.
[I 2026-04-29 15:22:01,126] Trial 58 finished with value: 0.6466348477501241 and parameters: {'regressor': 'KNN', 'n_neighbors': 18}. Best is trial 51 with value: 0.6989907491470608.
[I 2026-04-29 15:22:01,883] Trial 59 finished with value: 0.6983778572048369 and parameters: {'regressor': 'SVR', 'C': 9.138814467709162, 'gamma': 0.0014138865225399855}. Best is trial 51 with value: 0.6989907491470608.
[I 2026-04-29 15:22:02,679] Trial 60 finished with value: 0.6989743990345977 and parameters: {'regressor': 'SVR', 'C': 6.852149964156028, 'gamma': 0.0010199887122682855}. Best is trial 51 with value: 0.6989907491470608.
[I 2026-04-29 15:22:03,428] Trial 61 finished with value: 0.6985262110839813 and parameters: {'regressor': 'SVR', 'C': 6.677539130361809, 'gamma': 0.001484384776057739}. Best is trial 51 with value: 0.6989907491470608.
[I 2026-04-29 15:22:04,194] Trial 62 finished with value: 0.6989606289358719 and parameters: {'regressor': 'SVR', 'C': 6.93166077899982, 'gamma': 0.0010637817931074822}. Best is trial 51 with value: 0.6989907491470608.
[I 2026-04-29 15:22:04,999] Trial 63 finished with value: 0.6983107457308719 and parameters: {'regressor': 'SVR', 'C': 7.900710632813082, 'gamma': 0.0015387977302413875}. Best is trial 51 with value: 0.6989907491470608.
[I 2026-04-29 15:22:05,789] Trial 64 finished with value: 0.6967837999280967 and parameters: {'regressor': 'SVR', 'C': 6.083610954095274, 'gamma': 0.0023845939592676644}. Best is trial 51 with value: 0.6989907491470608.
[I 2026-04-29 15:22:06,585] Trial 65 finished with value: 0.6989809735392731 and parameters: {'regressor': 'SVR', 'C': 7.796964997404356, 'gamma': 0.0010049534903260123}. Best is trial 51 with value: 0.6989907491470608.
[I 2026-04-29 15:22:07,586] Trial 66 finished with value: 0.6757818018452488 and parameters: {'regressor': 'SVR', 'C': 7.96028814332384, 'gamma': 0.009959294702691836}. Best is trial 51 with value: 0.6989907491470608.
[I 2026-04-29 15:22:08,454] Trial 67 finished with value: 0.6867960307034955 and parameters: {'regressor': 'SVR', 'C': 5.671006529230619, 'gamma': 0.005952932903506671}. Best is trial 51 with value: 0.6989907491470608.
[I 2026-04-29 15:22:08,482] Trial 68 finished with value: 0.11030212889871716 and parameters: {'regressor': 'ElasticNet', 'alpha': 2.9348828396012565, 'l1_ratio': 0.2391556643615101}. Best is trial 51 with value: 0.6989907491470608.
[I 2026-04-29 15:22:09,300] Trial 69 finished with value: 0.6944605320938348 and parameters: {'regressor': 'SVR', 'C': 6.295826663862969, 'gamma': 0.0030918576223936786}. Best is trial 51 with value: 0.6989907491470608.
[I 2026-04-29 15:22:10,064] Trial 70 finished with value: 0.6980715473552856 and parameters: {'regressor': 'SVR', 'C': 9.198936066913626, 'gamma': 0.0015999376121266697}. Best is trial 51 with value: 0.6989907491470608.
[I 2026-04-29 15:22:10,881] Trial 71 finished with value: 0.698968402537707 and parameters: {'regressor': 'SVR', 'C': 7.012255714367272, 'gamma': 0.0010618660688880368}. Best is trial 51 with value: 0.6989907491470608.
[I 2026-04-29 15:22:11,679] Trial 72 finished with value: 0.6983311014638653 and parameters: {'regressor': 'SVR', 'C': 7.845532335938044, 'gamma': 0.0015143752513312673}. Best is trial 51 with value: 0.6989907491470608.
[I 2026-04-29 15:22:12,448] Trial 73 finished with value: 0.6989858281484597 and parameters: {'regressor': 'SVR', 'C': 6.687378370300812, 'gamma': 0.0010102276926893968}. Best is trial 51 with value: 0.6989907491470608.
[I 2026-04-29 15:22:13,282] Trial 74 finished with value: 0.69710046589579 and parameters: {'regressor': 'SVR', 'C': 6.990744678590635, 'gamma': 0.0021216517432146196}. Best is trial 51 with value: 0.6989907491470608.
[I 2026-04-29 15:22:14,062] Trial 75 finished with value: 0.6985687425790477 and parameters: {'regressor': 'SVR', 'C': 7.6260335619333075, 'gamma': 0.001417473595811243}. Best is trial 51 with value: 0.6989907491470608.
[I 2026-04-29 15:22:14,183] Trial 76 finished with value: 0.5585805508998927 and parameters: {'regressor': 'KNN', 'n_neighbors': 3}. Best is trial 51 with value: 0.6989907491470608.
[I 2026-04-29 15:22:14,959] Trial 77 finished with value: 0.6967855953006982 and parameters: {'regressor': 'SVR', 'C': 6.405248082613903, 'gamma': 0.0023284440885734106}. Best is trial 51 with value: 0.6989907491470608.
[I 2026-04-29 15:22:15,747] Trial 78 finished with value: 0.6989148396799947 and parameters: {'regressor': 'SVR', 'C': 5.385280699556951, 'gamma': 0.0010244653665442318}. Best is trial 51 with value: 0.6989907491470608.
[I 2026-04-29 15:22:16,551] Trial 79 finished with value: 0.6982111157231952 and parameters: {'regressor': 'SVR', 'C': 8.200236753496378, 'gamma': 0.0016299631770297371}. Best is trial 51 with value: 0.6989907491470608.
[I 2026-04-29 15:22:17,442] Trial 80 finished with value: 0.6919924086508448 and parameters: {'regressor': 'SVR', 'C': 8.857907327942636, 'gamma': 0.0032235146266564865}. Best is trial 51 with value: 0.6989907491470608.
[I 2026-04-29 15:22:18,200] Trial 81 finished with value: 0.6986854757738774 and parameters: {'regressor': 'SVR', 'C': 6.719627781997582, 'gamma': 0.0013205264673917523}. Best is trial 51 with value: 0.6989907491470608.
[I 2026-04-29 15:22:18,966] Trial 82 finished with value: 0.6989866178079888 and parameters: {'regressor': 'SVR', 'C': 7.044547511168888, 'gamma': 0.0010135050926127571}. Best is trial 51 with value: 0.6989907491470608.
[I 2026-04-29 15:22:19,839] Trial 83 finished with value: 0.6874426405365947 and parameters: {'regressor': 'SVR', 'C': 7.028878519874714, 'gamma': 0.005003028527104244}. Best is trial 51 with value: 0.6989907491470608.
[I 2026-04-29 15:22:20,642] Trial 84 finished with value: 0.6974426127183518 and parameters: {'regressor': 'SVR', 'C': 6.340568781384702, 'gamma': 0.002115776841528482}. Best is trial 51 with value: 0.6989907491470608.
[I 2026-04-29 15:22:21,462] Trial 85 finished with value: 0.6979852112576601 and parameters: {'regressor': 'SVR', 'C': 7.746938083168104, 'gamma': 0.001786505394277325}. Best is trial 51 with value: 0.6989907491470608.
[I 2026-04-29 15:22:21,485] Trial 86 finished with value: -0.0005472004134360109 and parameters: {'regressor': 'ElasticNet', 'alpha': 8.188366794157892, 'l1_ratio': 0.7934977386821596}. Best is trial 51 with value: 0.6989907491470608.
[I 2026-04-29 15:22:22,234] Trial 87 finished with value: 0.6986720668235662 and parameters: {'regressor': 'SVR', 'C': 7.408714569905895, 'gamma': 0.0012929166663192928}. Best is trial 51 with value: 0.6989907491470608.
[I 2026-04-29 15:22:23,017] Trial 88 finished with value: 0.6979644571498327 and parameters: {'regressor': 'SVR', 'C': 6.0842003881484805, 'gamma': 0.0019736874223957334}. Best is trial 51 with value: 0.6989907491470608.
[I 2026-04-29 15:22:23,871] Trial 89 finished with value: 0.6952500094806096 and parameters: {'regressor': 'SVR', 'C': 8.049086844240643, 'gamma': 0.002496254677210219}. Best is trial 51 with value: 0.6989907491470608.
[I 2026-04-29 15:22:24,023] Trial 90 finished with value: 0.6372377628474352 and parameters: {'regressor': 'KNN', 'n_neighbors': 30}. Best is trial 51 with value: 0.6989907491470608.

In [103]:
print(study1.best_trial.params)
print(study1.best_trial.value)

{'regressor': 'SVR', 'C': 7.015283273654784, 'gamma': 0.0010137226360850196}
0.6989907491470608

In [104]:
best_model = XGBRegressor(n_estimators=study0.best_trial.params["n_estimators"], 
                    max_depth=study0.best_trial.params["max_depth"], 
                    learning_rate=study0.best_trial.params["learning_rate"], 
                    random_state=42)

best_model.fit(x_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.022294413883118733, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=2, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=187, n_jobs=None,
             num_parallel_tree=None, ...)

In [105]:
y_pred=best_model.predict(x_test)

In [106]:
accuracy= r2_score(y_test, y_pred)
print("Test Accuracy:", accuracy)

Test Accuracy: 0.7151064351736465

# At this moment we are not focusing on the Accuracy of the model, here we just implementing the full End to End pipeline of MLops

In [107]:
import joblib
joblib.dump(best_model, r"D:\End to end project\Learning_MLOps\model_registry\best_model.pkl")

['D:\\End to end project\\Learning_MLOps\\model_registry\\best_model.pkl']